import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from  "@/components/sidebar";
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "BillEase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.variable} bg-white min-h-screen h-full flex`}>
        <Sidebar/>
        <div className="flex-1 px-5 py-2.5">{children}</div>
      </body>
    </html>
  );
}
